add button component and minor adjustments
PL-FE-MAY23-WebWeavers/product_catalog pull request #19
Opened 2023-11-02 15:54 UTC by Matylda-Lewandowska

minor adjustments and buttons as components

2023-11-02 16:53 UTC, Meg-Sowka requested changes

2023-11-02 16:53 UTC, Meg-Sowka commented on src/components/utils/ButtonFavs/buttonFavs.scss
> +
please remove empty lines

2023-11-02 16:53 UTC, Meg-Sowka commented on src/components/utils/ButtonFavs/buttonFavs.scss
> +
please remove empty lines

2023-11-02 22:13 UTC, domalewski requested changes
your good

2023-11-02 22:13 UTC, domalewski commented on src/components/utils/ButtonDefault/buttonDefault.scss
> +
is this a empty line?

2023-11-02 22:13 UTC, domalewski commented on src/components/utils/ButtonDefault/buttonDefault.scss
> +
omg there's another

2023-11-02 22:13 UTC, domalewski commented on src/styles/utils/_typography.scss
this look's suspicious

2023-11-03 10:49 UTC, Matylda-Lewandowska commented on src/styles/utils/_typography.scss
what do you mean?

2023-11-03 10:51 UTC, Matylda-Lewandowska commented on src/styles/utils/_typography.scss
ah empty line -.-

2023-11-03 11:33 UTC, Meg-Sowka approved these changes

2023-11-03 11:33 UTC, Meg-Sowka commented on src/components/utils/ButtonDefault/buttonDefault.scss
> +
please remove empty lines

2023-11-03 11:33 UTC, Meg-Sowka commented on src/components/utils/ButtonDefault/buttonDefault.scss
> +
please remove empty lines

2023-11-03 11:35 UTC, domalewski approved these changes

2023-11-03 11:36 UTC, merged