Slider with promo img
PL-FE-MAY23-WebWeavers/product_catalog pull request #25
Opened 2023-11-06 16:38 UTC by Matylda-Lewandowska

add **Slider.tsx** component;
add **slider.scss**;
add **swiper modules**;
fix some isssues **grid**;

2023-11-06 17:17 UTC, Matylda-Lewandowska commented
WIP
kilka rzeczy nie działa tak, jak powinno jutro pójdę na qna :)

2023-11-06 17:32 UTC, domalewski requested changes
this little buttons doesn't work :(

2023-11-08 09:01 UTC, Matylda-Lewandowska commented
> this little buttons doesn't work :(

Now works :D

2023-11-08 09:49 UTC, domalewski approved these changes

2023-11-08 09:56 UTC, merged